@host = https://localhost:5001

### Liste paginée avec filtres
GET {{host}}/api/products?page=1&pageSize=5&sortBy=price&sortDirection=asc&category=maison
Accept: application/json

### Détail produit
GET {{host}}/api/products/1
Accept: application/json

### Création
POST {{host}}/api/products
Content-Type: application/json

{
	"name": "Extracteur de jus premium",
	"description": "Moteur silencieux, 3 vitesses",
	"category": "electromenager",
	"price": 249.90,
	"currency": "EUR",
	"isPublished": true,
	"stockQuantity": 25
}

### Mise à jour partielle
PATCH {{host}}/api/products/1
Content-Type: application/json

{
	"Price": 199.99,
	"IsPublished": true
}
